name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  Tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Force node-gyp 9.0.0 in Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          npm install --global node-gyp@9.0.0
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - name: Install dependencies
        run: npm i

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
